spring.application.name=activiti-ai-dashboard
spring.datasource.url=postgresql://postgres:Iliveinbokaro@1@db.lnocjrtyupiuibexxova.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Iliveinbokaro@1
spring.jpa.hibernate.ddl-auto=update
